apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: app
          image: sit737-2025-prac7p
          imagePullPolicy: Never
          ports:
          - containerPort: 3111
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - port: 3111
      targetPort: 3111
      nodePort: 32506